version: '3'

services:
  libcor:
    build: .
    container_name: "LibCor"
    ports:
      - "8000:80"
    volumes:
      - ./app:/code
  minio:
    build: ./minio 
    volumes:
      - ./minio:/app
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
  minio_start:
    build: ./minio_start
    container_name: minio_start
    volumes:
      - ./minio_start:/app
    




