version: '3'

services:
  libcor:
    build: .
    container_name: "LibCor"
    ports:
      - "8000:80"
    volumes:
      - ./app:/code
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin



    




